on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Deploy container to Amazon EC2 Instance

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: http://ec2-3-87-26-35.compute-1.amazonaws.com:9000/hooks/webhook
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
